version: "3.7"
services:
  alfio:
    image: alfio/alf.io
    environment:
      POSTGRES_PORT_5432_TCP_PORT: 5432
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_ENV_POSTGRES_DB: alfio
      POSTGRES_ENV_POSTGRES_USERNAME: alfio
      POSTGRES_ENV_POSTGRES_PASSWORD: alfio
      SPRING_PROFILES_ACTIVE: jdbc-session,stdout
    ports:
      # - "8080:8080" #dev
      - "8443:8443"
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: alfio
      POSTGRES_USER: alfio
      POSTGRES_PASSWORD: alfio
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - data-volume:/var/lib/postgresql/data
  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt/webrootauth --email entramevip@gmail.com --agree-tos --no-eff-email --force-renewal -d entrame.vip
  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: renew --quiet
    restart: on-failure
  nginx:
    image: nginx:latest
    command: ["nginx", "-g", "daemon off;"]
    ports:
      # - "80:8080" #dev
      - "443:8443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - alfio
      - certbot
volumes:
  data-volume:
