version: "3.7"
services:
  alfio:
    image: alfio/alf.io
    environment:
      POSTGRES_PORT_5432_TCP_PORT: 5432
      POSTGRES_PORT_5432_TCP_ADDR: db
      POSTGRES_ENV_POSTGRES_DB: alfio
      POSTGRES_ENV_POSTGRES_USERNAME: alfio
      POSTGRES_ENV_POSTGRES_PASSWORD: alfio
      SPRING_PROFILES_ACTIVE: jdbc-session,stdout
    ports:
      # - "8080:8080" #dev
      - "8443:8443"
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: alfio
      POSTGRES_USER: alfio
      POSTGRES_PASSWORD: alfio
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
        mode: host
    volumes:
      - data-volume:/var/lib/postgresql/data
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx.dockerfile
    command: ["/bin/sh", "-c", "while ! [ -f /etc/letsencrypt/live/entrame.vip/fullchain.pem ]; do sleep 1; done && nginx -g 'daemon off;'"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - alfio
volumes:
  data-volume:
