  certbot:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email entramevip@gmail.com --agree-tos --no-eff-email --force-renewal -d entrame.vip
  certbot-renew:
    image: certbot/certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
    command: renew --quiet
    restart: on-failure